### ISSUE TITLE
.github/workflows/01-building-blocks.yaml isn't aligned with the problem statement of Practical Exercise 01 - Creating Our First Workflow

### ISSUE THREAD

**Issue by isalmanhaider** [lm-academy/github-actions-course#17]
Considering the problem statement at [Practical Exercise 01](https://www.udemy.com/course/mastering-github-actions-beginner-to-expert/learn/lecture/41501856#overview) this should be the final 01-building-blocks.yaml 

``` yml
name: 01 - Building Blocks

on:
  push:
  workflow_dispatch:

jobs:
  echo-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "Hello, World!"

  echo-goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: Failed step
        run: |
          echo "I will fail"
          exit 1
      - name: Say goodbye
        run: echo "Goodbye!"

```
